name: Python Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Start Chrome service for Selenium tests
      selenium-chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest

    - name: Run tests
      env:
        DISPLAY: :99
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: |
        pytest tests/

