name: Auto Commit and Push

on:
  push:
    branches:
      - main

jobs:
  commit_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make changes or run scripts
        run: |
          echo "Automated update at $(date)" >> update.log

      - name: Commit files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add update.log
          git commit -m "Automated update"
          git push origin main
