name: Python Selenium CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHONPATH: ./  # Ensure modules can be found
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Automated update" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/Fay-Hosseini/selenium-mouse-actions.git HEAD:main
